version: '3.3'
services:
  jenkins:
      container_name: jenkins-container
      restart: always # option in the compose file ensures that the Jenkins container remains up even after a reboot.
      image: jenkins/jenkins:lts
      ports:
        - 8080:8080
      volumes:
        - jenkins-home:/var/jenkins_home

  database:
    container_name: postgres-container
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 45s
      retries: 10
    volumes:
      - ./InitialScript/01_create_table.sql:/docker-entrypoint-initdb.d/01_create_table.sql
      - ./InitialScript/02_insert_data.sql:/docker-entrypoint-initdb.d/02_insert_data.sql
  dbeaver:
    container_name: dbeaver-container
    image: dbeaver/cloudbeaver
    ports: ["8000:8978"]
    hostname: gui
    volumes:
      - ./dbeaver:/opt/cloudbeaver/workspace
    tty: true
    depends_on:
      - database
    links:
      - database
  localstack:
    image: localstack/localstack
    ports:
      - '4567-4584:4567-4584'
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4567
      - SERVICES=s3

volumes:
  jenkins-home: # Volumes help ensure that data is not lost when a container is stopped, restarted, or removed.